apiVersion: v2
name: mijn-app
version: 1.0.0
dependencies:
  - name: ingress-nginx
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: cert-manager
    version: "v1.20.2"
    repository: "https://charts.jetstack.io"
